version: '3.4'

services:

  eauctiondb:
    container_name: eauctiondb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  eauctionsqldb:
    container_name: eauctionsqldb
    ports:
      - "1433:1433" 
    environment:
      SA_PASSWORD: "Odb12345678"
      ACCEPT_EULA: "Y"

  eauction.products.api: 
    container_name: eauctionproductsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://eauctiondb:27017"
    depends_on:
      - eauctiondb
    ports:
      - "8000:80"
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro

  eauction.sourcing.api:
    container_name: eauctionsourcingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://eauctiondb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - eauctiondb
      - rabbitmq
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "8001:80"

  eauction.order.webapi:
    container_name: eauctionorderapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnection=Server=eauctionsqldb;Database=OrderDb;User Id=sa;Password=Odb12345678"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - eauctionsqldb
      - rabbitmq
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "8002:80"

  eauction.apigateway:
    container_name: eauctionapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - eauction.products.api
      - eauction.sourcing.api
      - eauction.order.webapi
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "5000:80"
