version: '3.4'

services:

  eauctiondb:
    container_name: eauctiondb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  eauction.products.api: 
    container_name: eauctionproductsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://eauctiondb:27017"
    depends_on:
      - eauctiondb
    ports:
      - "8000:80"
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro

  eauction.sourcing.api:
    container_name: eauctionsourcingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://eauctiondb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - eauctiondb
      - rabbitmq
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "8001:80"
